### ISSUE TITLE
Sverchok Extra cannot start (after commit 3059d50)

### ISSUE THREAD

**Issue by rendetto** [portnov/sverchok-extra#31]
After 3059d50 (""Voronoi on Mesh" node.", 2020-11-16), Sverchok Extra cannot start and throws an error:

`Sverchok addon is not available. Sverchok-Extra will not work.
2020-11-22 15:56:13,536 [INFO] sverchok_extra.dependencies: Pygalmesh package is not available. Corresponding nodes will not be available
Traceback (most recent call last):
  File "D:\BlenderBin\blender-2.90.1-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\rendetto\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-extra-master\__init__.py", line 71, in <module>
    imported_modules = [icons] + make_node_list()
  File "C:\Users\rendetto\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-extra-master\__init__.py", line 67, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "D:\BlenderBin\blender-2.90.1-windows64\2.90\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\rendetto\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-extra-master\nodes\spatial\voronoi_on_mesh.py", line 28, in <module>
    from sverchok.utils.sv_bmesh_utils import recalc_normals
ImportError: cannot import name 'recalc_normals' from 'sverchok.utils.sv_bmesh_utils' (C:\Users\rendetto\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\utils\sv_bmesh_utils.py)
`

**Comment by portnov** [comment]
Should be fixed.

**Comment by rendetto** [comment]
Hmm.. did you published the fix. Those are the last changes in git I can see:

![last_git_changes](https://user-images.githubusercontent.com/66558924/99907247-6abf0000-2ce4-11eb-9445-23fc513d897b.jpg)

**Comment by rendetto** [comment]
Oh, sorry! It just came. And it's working!

Thanks

**Comment by rendetto** [comment]
Thanks :)
