### ISSUE TITLE
error upon activation (linux, python 3.9, blender 3.0)

### ISSUE THREAD

**Issue by Sinasta** [portnov/sverchok-extra#42]
I get this error upon activation:

Traceback (most recent call last):
  File "/usr/share/blender/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/__init__.py", line 120, in <module>
    imported_modules = [icons] + make_node_list()
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/__init__.py", line 116, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/nodes/sdf/estimate_bounds.py", line 11, in <module>
    from sverchok_extra.utils.sdf import *
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/utils/sdf.py", line 113, in <module>
    ease.linear,
NameError: name 'ease' is not defined

is there any dependency i need to install?

**Comment by portnov** [comment]
Should be fixed now. Please update the addon from master and try again.

**Comment by Sinasta** [comment]
Thank you for your help. The error changed to:

Traceback (most recent call last):
  File "/usr/share/blender/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/__init__.py", line 121, in <module>
    imported_modules = [icons] + make_node_list()
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/__init__.py", line 117, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/nodes/sdf/sdf_transition_linear.py", line 19, in <module>
    class SvExSdfLinearTransitionNode(bpy.types.Node, SverchCustomTreeNode):
  File "/home/sinasta/.config/blender/3.0/scripts/addons/sverchok-extra-master/nodes/sdf/sdf_transition_linear.py", line 28, in SvExSdfLinearTransitionNode
    easing_options = [(str(k), f.__name__, f.__name__, f.__name__, k) for k, f in easing_dict.items()]
NameError: name 'easing_dict' is not defined

**Comment by portnov** [comment]
Please update from master and try again.

**Comment by pliniobarraza** [comment]
I am getting the same error Sinasta reported, this time running python 3.10 and blender 3.6
