### ISSUE TITLE
Error Upon Activation.

### ISSUE THREAD

**Issue by Acidbuk** [portnov/sverchok-extra#43]
Activating sverchok-extra in Blender 2.93.4 Gives this error.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\LeonC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-extra-master\__init__.py", line 124, in <module>
    imported_modules = [icons] + make_node_list()
  File "C:\Users\LeonC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-extra-master\__init__.py", line 120, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\LeonC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-extra-master\nodes\sdf\sdf_generate.py", line 19, in <module>
    class SvExSdfGenerateNode(bpy.types.Node, SverchCustomTreeNode):
  File "C:\Users\LeonC\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-extra-master\nodes\sdf\sdf_generate.py", line 82, in SvExSdfGenerateNode
    default = sdf.mesh.BATCH_SIZE,
AttributeError: 'NoneType' object has no attribute 'mesh'

**Comment by portnov** [comment]
Should be fixed now. Please update addon from master and check again.

**Comment by Acidbuk** [comment]
Yep. Fixed now, Thank you for your help!
